name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '3.1.x'      

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests with 
        run: dotnet test --configuration Release  --collect:"XPlat Code Coverage"
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
         token: ${{ secrets.CODECOV_TOKEN }}
         file: ./BankNUnitTests/TestResults/**/coverage.cobertura.xml