name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests with NUnit
        run: dotnet test --configuration Release 
#       --collect:"XPlat Code Coverage"
#      - name: Upload coverage report to Codecov
#        uses: codecov/codecov-action@v2
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./TestResults/**/coverage.cobertura.xml